window.WORD_DATA = {
  "Sprout 3 A1": {
    "Lesson 1": [
      { "term": "adventure", "sentence": "have had quite an adventure", "jp": "すごい冒険をした" },
      { "term": "bowl", "sentence": "handed Sparky's bowl", "jp": "Sparkyのボウル（鉢）を渡した" },
      { "term": "bring [brought]", "sentence": "brought me to the door", "jp": "私をドアの前まで連れてきた" },
      { "term": "captain", "sentence": "a picture of me and the captain", "jp": "私と船長の写真" },
      { "term": "clap", "sentence": "clapped his hand to his forehead", "jp": "彼の額で手をポンと叩いた" },
      { "term": "crew", "sentence": "with the crew", "jp": "乗組員と一緒に" },
      { "term": "cross", "sentence": "crossed Lake Erie", "jp": "エリー湖を渡った" },
      { "term": "forehead", "sentence": "clapped his hand to his forehead", "jp": "彼の額で手をポンと叩いた" },
      { "term": "goldfish", "sentence": "remembered his goldfish", "jp": "彼の金魚を思い出した" },
      { "term": "mover", "sentence": "head mover", "jp": "引っ越し業者のリーダー" },
      { "term": "plenty", "sentence": "plenty of room", "jp": "十分な空間" },
      { "term": "quite", "sentence": "have had quite an adventure", "jp": "すごい冒険をした" },
      { "term": "remember", "sentence": "remembered his goldfish", "jp": "彼の金魚を思い出した" },
      { "term": "sail", "sentence": "sailed on a small cargo ship", "jp": "小さな貨物船に乗って航海した" },
      { "term": "stare", "sentence": "stared at each other", "jp": "互いをじっと見つめ合った" }
    ],
    "Lesson 2": [
      { "term": "energy", "sentence": "make energy", "jp": "エネルギーを作り出す" },
      { "term": "fill", "sentence": "be filled with water", "jp": "水で満たす" },
      { "term": "firm", "sentence": "stay firm and upright", "jp": "硬く直立した状態を保つ" },
      { "term": "flexible", "sentence": "strong and flexible", "jp": "丈夫で柔軟な" },
      { "term": "internal", "sentence": "internal tubes", "jp": "内部の管" },
      { "term": "lack", "sentence": "die from a lack of energy", "jp": "エネルギー不足で死ぬ" },
      { "term": "muscle", "sentence": "human muscles", "jp": "人間の筋肉" },
      { "term": "shape", "sentence": "keep their shape", "jp": "彼らの形を保つ" },
      { "term": "store", "sentence": "store water", "jp": "水を蓄える、水を貯める" },
      { "term": "strong", "sentence": "strong and flexible", "jp": "強く柔軟な" },
      { "term": "sugar", "sentence": "use this sugar for energy", "jp": "この糖分をエネルギーとして使用する" },
      { "term": "tissue", "sentence": "plant tissue", "jp": "植物組織" },
      { "term": "tube", "sentence": "internal tubes", "jp": "内部の管" },
      { "term": "upright", "sentence": "stay firm and upright", "jp": "硬く直立した状態を保つ" },
      { "term": "use", "sentence": "use water", "jp": "水を使用する" }
    ],
    "Lesson 3": [
      { "term": "break down", "sentence": "break down most foods", "jp": "ほとんどの食べ物を分解する" },
      { "term": "flow", "sentence": "keeps our blood flowing", "jp": "私たちの血が流れ続ける" },
      { "term": "function", "sentence": "three basic important functions", "jp": "基本的な3つの重要な機能" },
      { "term": "glue", "sentence": "acts like glue", "jp": "接着剤のような役割をする" },
      { "term": "keep", "sentence": "keeps our blood flowing", "jp": "私たちの血が流れ続ける" },
      { "term": "necessary", "sentence": "necessary", "jp": "必要な" },
      { "term": "nutrient", "sentence": "get important nutrients", "jp": "重要な栄養素を得る" },
      { "term": "organ", "sentence": "our muscles and organs", "jp": "私たちの筋肉と臓器" },
      { "term": "properly", "sentence": "flow properly", "jp": "ちゃんと流れる" },
      { "term": "separate", "sentence": "separate the nutrients from the waste", "jp": "栄養素を廃棄物から分離する" },
      { "term": "skin", "sentence": "keeps our skin strong", "jp": "私たちの皮膚を丈夫に保つ" },
      { "term": "survive", "sentence": "needs water to survive", "jp": "生存するためには水が必要だ" },
      { "term": "thick", "sentence": "too thick to flow", "jp": "流れるにはどろどろすぎる" },
      { "term": "tiny", "sentence": "tiny veins", "jp": "とても小さな静脈" },
      { "term": "waste", "sentence": "separate the nutrients from the waste", "jp": "栄養素を廃棄物から分離する" }
    ],
    "Lesson 4": [
      { "term": "appliance", "sentence": "all the appliances", "jp": "すべての家電製品" },
      { "term": "cooking", "sentence": "Grandma's irreplaceable cooking", "jp": "おばあさんのかけがえのない料理" },
      { "term": "figure out", "sentence": "figure out the rest", "jp": "その残りは理解しました" },
      { "term": "float", "sentence": "floating in it", "jp": "その中で浮かんでいる" },
      { "term": "gadget", "sentence": "many gadgets", "jp": "たくさんの道具" },
      { "term": "glow", "sentence": "glowed orange", "jp": "オレンジ色に輝いた" },
      { "term": "irreplaceable", "sentence": "Grandma's irreplaceable cooking", "jp": "おばあさんのかけがえのない料理" },
      { "term": "odorless", "sentence": "The gel is odorless.", "jp": "そのゲルは無臭です" },
      { "term": "panel", "sentence": "a panel slid open", "jp": "1つの板が滑るように開いた" },
      { "term": "pull out", "sentence": "pulled out a sausage", "jp": "ソーセージを1つ取り出した" },
      { "term": "reveal", "sentence": "revealing hanging pots and pans", "jp": "壁にかけられたポットと鍋が姿を現しながら" },
      { "term": "shelf [shelves]", "sentence": "on a shelf", "jp": "棚の上に" },
      { "term": "slide [slid]", "sentence": "a panel slid open", "jp": "1つの板が滑るように開いた" },
      { "term": "stay away", "sentence": "stay away from this kitchen", "jp": "この台所から離れていなさい" },
      { "term": "straight", "sentence": "went straight", "jp": "まっすぐ行った" }
    ],
    "Lesson 5": [
      { "term": "allow", "sentence": "allow computers to become even smaller", "jp": "コンピューターをより一層小さくしてくれる" },
      { "term": "connection", "sentence": "What's the connection?", "jp": "どんな関連性があるのでしょう？" },
      { "term": "create", "sentence": "create the solutions", "jp": "解決策を生み出す" },
      { "term": "deal with", "sentence": "deals with saving energy", "jp": "エネルギーの節約を扱う" },
      { "term": "device", "sentence": "energy storage devices", "jp": "エネルギーを保存する装置" },
      { "term": "electricity", "sentence": "store electricity", "jp": "電気を保存する" },
      { "term": "frame", "sentence": "in the frames", "jp": "メガネフレームの中に" },
      { "term": "inexpensive", "sentence": "inexpensive insulation", "jp": "安い断熱材" },
      { "term": "insulation", "sentence": "inexpensive insulation", "jp": "安い断熱材" },
      { "term": "man-made", "sentence": "man-made nano-materials", "jp": "人が作り出したナノ物質" },
      { "term": "pass through", "sentence": "keeping air from passing through", "jp": "空気が通過するのを防ぐ" },
      { "term": "promising", "sentence": "promising nanotechnology research", "jp": "有望なナノテクノロジーの研究" },
      { "term": "save", "sentence": "saves energy and money", "jp": "エネルギーとお金を節約する" },
      { "term": "storage", "sentence": "energy storage", "jp": "エネルギーを保存する" },
      { "term": "temperature", "sentence": "maintain temperatures", "jp": "温度を維持する" }
    ],
    "Lesson 6": [
      { "term": "advanced", "sentence": "the most advanced shoe", "jp": "最も進歩した靴" },
      { "term": "arch", "sentence": "arch", "jp": "土踏まず" },
      { "term": "brand new", "sentence": "some brand new shoes", "jp": "いくつかの真新しい靴" },
      { "term": "combine", "sentence": "combines the natural feel with added protection", "jp": "自然な感覚と保護する機能を兼ね備えている" },
      { "term": "extra", "sentence": "at no extra charge", "jp": "追加料金なし" },
      { "term": "fit ... like a glove", "sentence": "fits your foot like a glove", "jp": "あつらえたよう（手袋のように）にあなたの足にぴったり合う" },
      { "term": "last", "sentence": "lasts for one week", "jp": "1週間続けられる" },
      { "term": "material", "sentence": "mesh material", "jp": "メッシュ素材" },
      { "term": "metal", "sentence": "metal springs", "jp": "金属スプリング" },
      { "term": "protection", "sentence": "protection from scrapes and cuts", "jp": "すり傷と切り傷から保護" },
      { "term": "run out", "sentence": "until supplies run out", "jp": "供給品が品切れになるまで" },
      { "term": "sale", "sentence": "sale", "jp": "割引販売、バーゲン" },
      { "term": "shock", "sentence": "shock absorption", "jp": "衝撃吸収" },
      { "term": "supply", "sentence": "until supplies run out", "jp": "供給品が品切れになるまで" },
      { "term": "vest", "sentence": "bulletproof vests", "jp": "防弾チョッキ" }
    ]
  },
  "Other": {
    "Sample Lesson": [
      { "term": "example", "sentence": "This is an example", "jp": "これは例です" }
    ]
  },
  "Sprout 3 B3": {
    "Lesson 1": [
      { "term": "attract", "sentence": "attract some materials", "jp": "いくつかの物質を引き付ける" },
      { "term": "crawl", "sentence": "crawled toward the shed", "jp": "倉庫へ向かって這って行った" },
      { "term": "drawer", "sentence": "checked a drawer", "jp": "引き出しを調べる" },
      { "term": "from side to side", "sentence": "sweeping the magnet from side to side", "jp": "磁石を左右に掃くように動かしながら" },
      { "term": "iron", "sentence": "like iron", "jp": "鉄のような" },
      { "term": "magnet", "sentence": "found a magnet", "jp": "磁石を見つけた" },
      { "term": "marked", "sentence": "a drawer marked “screws”", "jp": "「ネジ」と表示された引き出し" },
      { "term": "material", "sentence": "magnetic materials", "jp": "磁気のある物質" },
      { "term": "missing", "sentence": "the missing screw", "jp": "なくなったネジ" },
      { "term": "reach for", "sentence": "reached for the screw", "jp": "ネジを取ろうと手を伸ばした" },
      { "term": "retrace", "sentence": "retraced their steps", "jp": "彼等の足取りを振り返る" },
      { "term": "screw", "sentence": "need another screw", "jp": "ネジがもう1つ必要だ" },
      { "term": "stick [stuck]", "sentence": "several screws stuck to it", "jp": "それについているいくつかのネジ" },
      { "term": "sweep", "sentence": "sweeping the magnet", "jp": "磁石を掃くように動かしながら" },
      { "term": "tool shed", "sentence": "to the tool shed", "jp": "工具倉庫へ" }
    ],
    "Lesson 2": [
      { "term": "affect", "sentence": "affect the electronics of a refrigerator", "jp": "冷蔵庫の電子装置に影響を及ぼす" },
      { "term": "bill", "sentence": "the electricity bill", "jp": "電気料金" },
      { "term": "clear", "sentence": "clear some space", "jp": "空間を少しあけて" },
      { "term": "collection", "sentence": "had a large collection", "jp": "収集物をたくさん持っていた" },
      { "term": "cover", "sentence": "was covered with them", "jp": "それらで覆われていた" },
      { "term": "electricity", "sentence": "the electricity bill", "jp": "電気代" },
      { "term": "fascinated", "sentence": "became fascinated", "jp": "魅せられた" },
      { "term": "fridge", "sentence": "on the fridge", "jp": "冷蔵庫の上に" },
      { "term": "increase", "sentence": "increases the electricity bill", "jp": "電気代を上げる" },
      { "term": "plead", "sentence": "She pleaded.", "jp": "彼女は哀願した" },
      { "term": "powerful", "sentence": "uses a much more powerful magnet", "jp": "より一層強力な磁石を利用する" },
      { "term": "space", "sentence": "clear some space", "jp": "空間を少しあけて" },
      { "term": "waste", "sentence": "wasted power", "jp": "電気を浪費した" },
      { "term": "weak", "sentence": "too small and weak", "jp": "とても小さくて弱い" },
      { "term": "whole", "sentence": "the whole fridge", "jp": "冷蔵庫全体" }
    ],
    "Lesson 3": [
      { "term": "ability", "sentence": "their ability to return to specific places", "jp": "特定の場所へ戻ってくる彼等の能力" },
      { "term": "beak", "sentence": "in their beaks", "jp": "彼等のくちばしの中に" },
      { "term": "conduct", "sentence": "conduct a study", "jp": "研究を行う" },
      { "term": "convince", "sentence": "convinced many scientists", "jp": "多くの科学者を確信させた" },
      { "term": "experiment", "sentence": "a series of experiments", "jp": "一連の実験" },
      { "term": "limit", "sentence": "limited the pigeons’ ability", "jp": "ハトの能力を制限した" },
      { "term": "magnetic field", "sentence": "recognize magnetic fields", "jp": "磁場を認知する" },
      {
        "term": "magnetized", "sentence": "tiny, magnetized particles",
        "jp": "とても小さい磁気を帯びた粒子"
      },
      { "term": "migratory", "sentence": "certain migratory birds", "jp": "ある渡り鳥" },
      { "term": "particle", "sentence": "tiny, magnetized particles", "jp": "とても小さい磁気を帯びた粒子" },
      { "term": "recognize", "sentence": "recognize magnetic fields", "jp": "磁場を認知する" },
      { "term": "rule out", "sentence": "rule out smell as a factor", "jp": "要因として匂いを除く" },
      { "term": "sense", "sentence": "sense magnetic fields", "jp": "磁場を感知する" },
      { "term": "smell", "sentence": "use smell", "jp": "匂いを利用する" },
      { "term": "tiny", "sentence": "tiny, magnetized particles", "jp": "とても小さい磁気を帯びた粒子" }
    ],
    "Lesson 4": [
      { "term": "bend over [bent over]", "sentence": "bent over in a field", "jp": "野原で前かがみになった" },
      { "term": "choice", "sentence": "Millet’s choice", "jp": "ミレーの選択" },
      { "term": "controversial", "sentence": "very controversial", "jp": "とても論争の的になる" },
      { "term": "drag", "sentence": "dragged Olga", "jp": "Olgaを連れ回した" },
      { "term": "exhibition", "sentence": "the art exhibition", "jp": "美術展覧会" },
      { "term": "farming", "sentence": "poor farming women", "jp": "貧しい農村の女性たち" },
      { "term": "gently", "sentence": "touched Olga’s shoulder gently", "jp": "Olgaの肩をやさしく触った" },
      { "term": "grain", "sentence": "gathering grain", "jp": "穀物を集めながら" },
      { "term": "hang [hung]", "sentence": "hung her head", "jp": "彼女は頭をうなだれた" },
      { "term": "look up", "sentence": "looked up The Gleaners", "jp": "「落穂拾い」を調べてみた" },
      { "term": "lower class", "sentence": "support for the lower classes", "jp": "下級階級のための支持" },
      { "term": "opposite", "sentence": "in the opposite direction", "jp": "反対の方向へ" },
      { "term": "paper", "sentence": "wrote a paper", "jp": "論文を書いた" },
      {
        "term": "sigh", "sentence": "sighed deeply",
        "jp": "深いため息をついた"
      },
      { "term": "support", "sentence": "support for the lower classes", "jp": "下級階級のための支持" }
    ],
    "Lesson 5": [
      { "term": "bake", "sentence": "bake the pieces at 170°C", "jp": "それらを170度で焼く" },
      { "term": "bite-sized", "sentence": "bite-sized triangles", "jp": "ひと口サイズの三角形のもの" },
      { "term": "corn flour", "sentence": "mix corn flour and water", "jp": "トウモロコシの粉と水を混ぜる" },
      { "term": "crunchy", "sentence": "a crunchy snack", "jp": "パリパリと音をたてるお菓子" },
      { "term": "dough", "sentence": "make dough", "jp": "生地を作る" },
      { "term": "flat", "sentence": "roll them flat", "jp": "それらを平たく伸ばす" },
      { "term": "golden", "sentence": "golden brown", "jp": "金色に光る茶色" },
      { "term": "greased", "sentence": "a greased baking pan", "jp": "油をひいた焼き型" },
      { "term": "heat", "sentence": "heat them", "jp": "それらを加熱する" },
      { "term": "mix", "sentence": "mix corn flour and water", "jp": "トウモロコシの粉と水を混ぜる" },
      { "term": "originate", "sentence": "originated in Latin America", "jp": "ラテンアメリカに由来した" },
      { "term": "plastic wrap", "sentence": "two pieces of plastic wrap", "jp": "2つのビニールラップ" },
      { "term": "roll", "sentence": "roll them flat", "jp": "それらを平たく伸ばす" },
      { "term": "sprinkle", "sentence": "sprinkle them with salt", "jp": "それらに塩を振りかける" },
      { "term": "sticky", "sentence": "too sticky", "jp": "とてもべとつく" }
    ],
    "Lesson 6": [
      { "term": "braided", "sentence": "tightly braided", "jp": "堅く編まれた" },
      { "term": "bundle", "sentence": "tight bundles", "jp": "堅い束" },
      { "term": "digest", "sentence": "easily digest it", "jp": "それを容易に消化する" },
      { "term": "flexible", "sentence": "sturdy and flexible", "jp": "丈夫で伸縮性のある" },
      { "term": "harvest", "sentence": "harvest grains", "jp": "穀物を収穫する" },
      { "term": "last", "sentence": "last for up to 50 years", "jp": "最大50年まで持続する" },
      { "term": "leave [left]", "sentence": "are left with straw", "jp": "わらだけ残っている" },
      { "term": "rope", "sentence": "like rope", "jp": "縄のように" },
      { "term": "shade", "sentence": "provide good shade", "jp": "良い日陰を提供する" },
      { "term": "straw", "sentence": "are left with straw", "jp": "わらだけ残っている" },
      { "term": "sturdy", "sentence": "sturdy and flexible", "jp": "丈夫で伸縮性のある" },
      { "term": "tie", "sentence": "tie pieces of straw together", "jp": "わらをひとまとめに縛る" },
      {
        "term": "tight", "sentence": "tight bundles",
        "jp": "堅い束"
      },
      { "term": "wearable", "sentence": "make wearable items", "jp": "身につけられるものをつくる" },
      { "term": "woven", "sentence": "woven to make hats", "jp": "編んで帽子を作る" }
    ]
  },
  "Sapling 1A1": {
    "Lesson 1": [
      { "term": "according to", "sentence": "according to the study", "jp": "その研究によると" },
      { "term": "cheer up", "sentence": "help cheer us up", "jp": "私たちが元気づくようにする" },
      { "term": "close", "sentence": "a close friend", "jp": "親しい友達" },
      { "term": "company", "sentence": "make good company", "jp": "一緒にいるのに良い" },
      { "term": "conversation", "sentence": "have a conversation", "jp": "会話・対話を交わす" },
      { "term": "health", "sentence": "be good for your health", "jp": "健康に良い" },
      { "term": "individual", "sentence": "surveyed 1,500 individuals", "jp": "1500人の人々をアンケート調査した" },
      { "term": "main", "sentence": "two main ways", "jp": "ふたつの主な方法" },
      { "term": "mental", "sentence": "mental health", "jp": "精神的な健康" },
      { "term": "observe", "sentence": "after observing them", "jp": "彼らを観察した後" },
      { "term": "relationship", "sentence": "a healthy relationship", "jp": "健全な関係" },
      { "term": "spend", "sentence": "spend time with friends", "jp": "友達と時間を過ごす" },
      { "term": "study", "sentence": "one recent study", "jp": "最近のある研究" },
      { "term": "take care of", "sentence": "take better care of our bodies", "jp": "私たちの体をもっとよく世話する" },
      { "term": "visit", "sentence": "visit a doctor", "jp": "医者を訪ねる" }
    ],
    "Lesson 2": [
      { "term": "average", "sentence": "the average answer", "jp": "平均的な答え" },
      { "term": "befriend", "sentence": "befriend someone", "jp": "誰かと友達になる" },
      { "term": "discussion", "sentence": "a deep discussion", "jp": "深い議論" },
      { "term": "expression", "sentence": "a friend's expressions", "jp": "友達の表情" },
      { "term": "interaction", "sentence": "live interactions", "jp": "ライブインタラクション、リアルタイムの会話" },
      { "term": "intimate", "sentence": "intimate secrets", "jp": "私的な秘密" },
      { "term": "meaningful", "sentence": "the most meaningful", "jp": "最も意味のある" },
      { "term": "participant", "sentence": "thousands of participants", "jp": "何千人もの参加者" },
      { "term": "post", "sentence": "post on your online profile", "jp": "オンラインプロフィールに投稿する" },
      { "term": "replace", "sentence": "replace offline friends", "jp": "オフラインの友達に取って代わる" },
      { "term": "response", "sentence": "get several responses", "jp": "いくつかの返答を得る" },
      { "term": "result", "sentence": "the results of the survey", "jp": "調査の結果" },
      { "term": "share", "sentence": "share their deepest secrets", "jp": "彼らの最も深い秘密を分かち合う" },
      { "term": "support", "sentence": "this kind of support", "jp": "このような励まし" },
      { "term": "tone", "sentence": "the tone of a friend's voice", "jp": "友達の声のトーン" }
    ],
    "Lesson 3": [
      { "term": "benefit", "sentence": "benefit from cleaner fish", "jp": "掃除魚から恩恵を得る" },
      { "term": "bind", "sentence": "bind to a fish", "jp": "魚にくっつく" },
      { "term": "conflict", "sentence": "better than conflict", "jp": "争いよりも良い" },
      { "term": "cooperative", "sentence": "this kind of cooperative relationship", "jp": "このような協力的な関係" },
      { "term": "example", "sentence": "examples of symbiosis", "jp": "共生の例" },
      { "term": "feed on", "sentence": "feed on parasites", "jp": "寄生虫を餌にする" },
      { "term": "friendly", "sentence": "a friendly relationship", "jp": "友好的な関係" },
      { "term": "in place", "sentence": "swimming in place", "jp": "いつもの場所で泳ぐ" },
      { "term": "include", "sentence": "including sharks", "jp": "サメを含む" },
      { "term": "invisible", "sentence": "invisible creatures", "jp": "目に見えない生き物" },
      { "term": "meal", "sentence": "a free meal", "jp": "無料(ただ)の食事" },
      { "term": "nature", "sentence": "everywhere in nature", "jp": "自然界のいたるところで" },
      { "term": "signal", "sentence": "makes a signal", "jp": "信号を発する" },
      { "term": "species", "sentence": "small species of fish", "jp": "小さな魚種" },
      { "term": "unlikely", "sentence": "an unlikely friendship", "jp": "意外な友情" }
    ],
    "Lesson 4": [
      { "term": "athlete", "sentence": "see athletes stretching", "jp": "運動選手がストレッチしているのを目にする" },
      { "term": "blood", "sentence": "blood flow to the muscles", "jp": "筋肉への血流" },
      { "term": "cause", "sentence": "cause more injuries", "jp": "より多くの怪我を引き起こす" },
      { "term": "common", "sentence": "the most common form", "jp": "最もよくある形態" },
      { "term": "competition", "sentence": "before their competitions begin", "jp": "彼らの競技が始まる前に" },
      { "term": "hold", "sentence": "hold the same position", "jp": "同じ姿勢を維持する" },
      { "term": "injury", "sentence": "a serious injury", "jp": "重傷、深刻な負傷" },
      { "term": "lay", "sentence": "laying your legs flat", "jp": "あなたの両足を平らに置くこと" },
      { "term": "muscle", "sentence": "the strength of muscles", "jp": "筋肉の力" },
      { "term": "pain", "sentence": "feeling pain", "jp": "痛みを感じること" },
      { "term": "prepare", "sentence": "prepare your muscles for exercise", "jp": "運動のためにあなたの筋肉を準備させる" },
      { "term": "prevent", "sentence": "prevent injuries", "jp": "けがを予防する" },
      { "term": "static", "sentence": "static stretching", "jp": "静的ストレッチ" },
      { "term": "swing", "sentence": "swinging your arms", "jp": "あなたの両腕を振ること" },
      { "term": "work out", "sentence": "before working out", "jp": "運動する前" }
    ],
    "Lesson 5": [
      { "term": "affect", "sentence": "affect your height", "jp": "あなたの身長に影響を与える" },
      { "term": "bend", "sentence": "bending your knees", "jp": "ひざを曲げること" },
      { "term": "continue", "sentence": "will usually continue growing", "jp": "普通、成長し続けるだろう" },
      { "term": "diet", "sentence": "your healthy diet", "jp": "あなたの健康的な食生活" },
      { "term": "ground", "sentence": "touch the ground", "jp": "地面に着く" },
      { "term": "height", "sentence": "affect your height", "jp": "あなたの身長に影響を与える" },
      { "term": "lie down", "sentence": "lie down with your back to the floor", "jp": "床に仰向けになって横になる" },
      { "term": "lift", "sentence": "lift your legs", "jp": "あなたの脚を持ち上げる" },
      { "term": "maintain", "sentence": "maintain your full height", "jp": "あなたの最大限の身長を維持する" },
      { "term": "posture", "sentence": "better posture", "jp": "よりよい姿勢" },
      { "term": "reach", "sentence": "reach the end", "jp": "終わりに至る" },
      { "term": "spine", "sentence": "stretch your joints and spine", "jp": "あなたの関節と脊椎を伸ばす" },
      { "term": "throughout", "sentence": "throughout the day", "jp": "一日中" },
      { "term": "tone", "sentence": "tone your stomach", "jp": "あなたのお腹に弾力性を持たせる" },
      { "term": "trick", "sentence": "a trick for staying at your full height", "jp": "あなたの身長を最大限に保つための秘訣" }
    ],
    "Lesson 6": [
      { "term": "active", "sentence": "be more active", "jp": "もっと活動的に生きなさい" },
      { "term": "afford", "sentence": "can't afford gym memberships", "jp": "ジムの会員になる余裕がない" },
      { "term": "entire", "sentence": "the entire gym", "jp": "ジム全体" },
      { "term": "free", "sentence": "the memberships are free", "jp": "会員権は無料である" },
      { "term": "glance", "sentence": "glanced at each other", "jp": "お互いをちらっと見た" },
      { "term": "lounge", "sentence": "look in the lounge", "jp": "休憩室を見回す" },
      { "term": "membership", "sentence": "signed us all up for membership", "jp": "私たちみんなを会員に登録させた" },
      { "term": "nudge", "sentence": "nudging Bianca with his elbow", "jp": "Biancaを彼のひじでそっと突きながら" },
      { "term": "ready", "sentence": "ready for the gym", "jp": "ジムに行く準備ができた" },
      { "term": "remote", "sentence": "holding the remote", "jp": "リモコンを持って" },
      { "term": "roll", "sentence": "rolled her eyes", "jp": "彼女の目をくりくりさせた" },
      { "term": "sign up", "sentence": "signed us all up for membership", "jp": "私たちみんなを会員に登録させた" },
      { "term": "sound", "sentence": "sounds pretty expensive", "jp": "かなり高そうだ" },
      { "term": "treadmill", "sentence": "the treadmill section", "jp": "ランニングマシンコーナー" },
      { "term": "turn off", "sentence": "the TV turned off", "jp": "テレビが消えた" }
    ]
  }
};
